# Generated by Django 4.2.1 on 2023-06-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_discount', models.PositiveIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('expiry_date', models.DateField()),
                ('minimum_purchase', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
