# Generated by Django 4.2.1 on 2023-06-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=300)),
                ('time_stamp', models.DateTimeField()),
            ],
        ),
    ]
